# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run : cd ./docs
    - run: yarn
    - run: yarn build
    - run : cd
    - name: Commit files
      run: |
        cd ./docs/src/.vuepress/dist
        git init
        git config --local user.email "pcjpcj2@gmail.com"
        git config --local user.name "ChangJoo Park"
        git add -A
        git commit -m "Deploy" -a
        git remote -v
        git push -f https://changjoo-park:${{ secrets.GITHUB_TOKEN }}@github.com/changjoo-park/write.git master:gh-pages